version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "**/*.d.ts"
  - "tests/pyspectrum/"
  - "examples/"

